security:
    encoders:
        VelovitoBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10

    role_hierarchy:
        ROLE_USER: IS_AUTHENTICATED_ANONYMOUSLY
        ROLE_ADMIN: ROLE_USER

    providers:
        main:
            entity:
                class: VelovitoBundle\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:  ^/
            anonymous: true
            form_login:
                check_path: login_check
                login_path: login
                always_use_default_target_path: true
                default_target_path: homepage
            logout:
                path: logout
                target: login

    access_control:
        - { path: ^/user, roles: [ROLE_USER] }
        - { path: ^/admin, roles: [ROLE_ADMIN] }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
