# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    advertisement_service:
        class: AppBundle\Model\AdvertisementModel
        arguments: ["@doctrine.orm.entity_manager"]

    twig.cast_to_array:
         class: AppBundle\Twig\CastToArrayExtension
         tags:
             - { name: twig.extension }