# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    model.maintenance:
        class: AppBundle\Model\Maintenance\MaintenanceModel
        arguments: ["@doctrine.orm.entity_manager"]

    model.default:
        class: AppBundle\Model\DefaultModel
        arguments: ["@doctrine.orm.entity_manager", "@kernel", "@session"]

    model.security:
        class: AppBundle\Model\SecurityModel
        arguments: ["@doctrine.orm.entity_manager", "@kernel"]

    twig.cast_to_array:
        class: AppBundle\Twig\CastToArrayExtension
        tags:
            - { name: twig.extension }

    wsse.security.authentication.provider:
        class: AppBundle\Security\Authentication\Provider\WsseProvider
        arguments: ["", "", "@session"]

    wsse.security.authentication.listener:
        class: AppBundle\Security\Firewall\WsseListener
        arguments: ["@security.token_storage", "@security.authentication.manager", "@session"]
