-
    id: 100
    alias: chassis
    name: Ходовая часть
    children:
        -
            id: 101
            alias: rims
            name: Обода
        -
            id: 102
            alias: spokes
            name: Спицы
        -
            id: 103
            alias: tyres
            name: Покрышки

-
    id: 200
    alias: brakes
    name: Тормоза
    children:
        -
            id: 201
            alias: disk_brakes
            name: Дисковые тормоза
        -
            id: 205
            alias: disk_brakes
            name: Ободные тормоза
        -
            id: 210
            alias: brakes_inventory
            name: Колодки, фиттинги, гидролинии
        -
            id: 215
            alias: brakes_fluids
            name: Тормозная жидкость, химия
        -
            id: 220
            alias: adapters
            name: Адаптеры для калипера

