-
    alias: wheels
    name: Колеса
    children:
        -
            alias: rims
            name: Обода
        -
            alias: spokes
            name: Спицы
        -
            alias: tyres
            name: Покрышки
        -
            alias: hubs
            name: Втулки

-
    alias: chassis
    name: Ходовая часть
    children:
        -
            alias: chain
            name: Цепи
        -
            alias: systems
            name: Системы
        -
            alias: shatunis
            name: Шатуны

-
    alias: brakes
    name: Тормоза
    children:
        -
            alias: disk_brakes
            name: Дисковые тормоза
        -
            alias: v_brakes
            name: Ободные тормоза
        -
            alias: brakes_inventory
            name: Колодки, фиттинги, гидролинии
        -
            alias: brakes_fluids
            name: Тормозная жидкость, химия
        -
            alias: adapters
            name: Адаптеры для калипера
