-
    alias: chassis
    name: Ходовая часть

-
    alias: rims
    name: Обода

-
    alias: spokes
    name: Спицы

-
    alias: tyres
    name: Покрышки

-
    alias: brakes
    name: Тормоза

-
    alias: adapters
    name: Адаптеры для калипера

-
    alias: accessories
    name: Аксессуары к тормозам

-
    alias: hydrolines_and_fittings
    name: Гидролинии и фиттинги

-
    alias: misc
    name: Запчасти для тормозов
