login_check:
    path: /login-check

logout:
    path: /logout

#routes for real pages
login:
    path: /login
    defaults:
        _controller: VelovitoBundle:Security:login
        title: Вход

registration:
    path: /registration
    defaults:
        _controller: VelovitoBundle:Security:registration
        title: Регистрация

#--------------------------------------------------------
ajax_upload_photo:
    path:     /ajax-upload-photo
    defaults: { _controller: VelovitoBundle:Ajax:uploadPhoto }

velovito:
    path:     /velovito
    defaults: { _controller: VelovitoBundle:Default:velovito }

homepage:
    path:     /
    defaults: { _controller: VelovitoBundle:Default:index }

catalog:
    path:     /catalog
    defaults: { _controller: VelovitoBundle:Default:index }


profile:
    path:     /profile
    defaults: { _controller: VelovitoBundle:User:profile }


my_ads:
    path:     /my_adverts
    defaults: { _controller: VelovitoBundle:User:myAds }


favorites:
    path:     /favorites
    defaults: { _controller: VelovitoBundle:User:favorites }

ad_new:
    path:     /unpublish-new
    defaults: { _controller: VelovitoBundle:Advert:newAdvert }

ad_edit:
    path:     /edit-advert/{advertId}
    defaults: { _controller: VelovitoBundle:Advert:editAdvert, advertId: null }

ad_unpublish:
    path:     /unpublish-advert/{advertId}
    defaults: { _controller: VelovitoBundle:Advert:unpublishAdvert }

ad_delete:
    path:     /unpublish-delete
    defaults: { _controller: VelovitoBundle:Advert:editAdvert }

ad_view:
    path:     /view-advert/{advertId}
    defaults: { _controller: VelovitoBundle:Advert:viewAdvert, advertId: null }
