login_check:
    path: /login-check

logout:
    path: /logout

#routes for real pages
login:
    path: /login
    defaults:
        _controller: VelovitoBundle:Security:login
        title: Вход

registration:
    path: /registration
    defaults:
        _controller: VelovitoBundle:Security:registration
        title: Регистрация

vk_auth_token:
    path: /vk-auth-token
    defaults:
        _controller: VelovitoBundle:Security:vkAuthToken
        title: Регистрация через ВК

vk_auth_success:
    path: /vk-auth-success
    defaults:
        _controller: VelovitoBundle:Security:vkAuthSuccess
        title: Регистрация через ВК

#--------------------------------------------------------

admin_dashBoard:
    path:     /admin
    defaults: { _controller: VelovitoBundle:Admin:dashBoard }

admin_list_products:
    path:     /admin/list-products
    defaults: { _controller: VelovitoBundle:Admin:listProducts }

admin_list_categories:
    path:     /admin/list-categories
    defaults: { _controller: VelovitoBundle:Admin:listCategories }

admin_edit_product:
    path:     /admin/edit-product/{id}
    defaults: { _controller: VelovitoBundle:Admin:editProduct }

admin_edit_category:
    path:     /admin/edit-category/{id}
    defaults: { _controller: VelovitoBundle:Admin:editCategory }

admin_product_moderate_adverts:
    path:     /admin
    defaults: { _controller: VelovitoBundle:Admin:dashBoard }
#--------------------------------------------------------

ajax_upload_photo:
    path:     /ajax-upload-photo
    defaults: { _controller: VelovitoBundle:Ajax:uploadPhoto }

#--------------------------------------------------------

velovito:
    path:     /velovito
    defaults: { _controller: VelovitoBundle:Default:velovito }

homepage:
    path:     /
    defaults: { _controller: VelovitoBundle:Default:index }

catalog:
    path:     /catalog
    defaults: { _controller: VelovitoBundle:Default:index }


profile:
    path:     /profile
    defaults: { _controller: VelovitoBundle:User:profile }


my_ads:
    path:     /my-adverts
    defaults: { _controller: VelovitoBundle:User:myAds }


favorites:
    path:     /favorite-adverts
    defaults: { _controller: VelovitoBundle:User:favoriteAdverts }

advert_new:
    path:     /new-advert
    defaults: { _controller: VelovitoBundle:Advert:addAdvert }

advert_edit:
    path:     /edit-advert/{advertId}
    defaults: { _controller: VelovitoBundle:Advert:editAdvert}

advert_unpublish:
    path:     /unpublish-advert/{advertId}
    defaults: { _controller: VelovitoBundle:Advert:unpublishAdvert }

advert_delete:
    path:     /unpublish-delete
    defaults: { _controller: VelovitoBundle:Advert:asdAdvert }

advert_view:
    path:     /view-advert/{advertId}
    defaults: { _controller: VelovitoBundle:Advert:viewAdvert, advertId: null }

adverts_search:
    path:     /search-adverts
    defaults: { _controller: VelovitoBundle:Advert:searchAdvert, advertId: null }

view_category:
    path:     /view-category
    defaults: { _controller: VelovitoBundle:Advert:viewCategory}
