login_check:
    path: /login-check

logout:
    path: /logout

test:
    path: /test
    defaults:
        _controller: VelovitoBundle:Test:test

#routes for real pages
login:
    path: /login
    defaults:
        _controller: VelovitoBundle:Security:login
        title: Вход

registration:
    path: /registration
    defaults:
        _controller: VelovitoBundle:Security:registration
        title: Регистрация

vk_auth_token:
    path: /vk-auth-token
    defaults:
        _controller: VelovitoBundle:Security:vkAuthToken
        title: Регистрация через ВК

vk_auth_success:
    path: /vk-auth-success
    defaults:
        _controller: VelovitoBundle:Security:vkAuthSuccess
        title: Регистрация через ВК

#--------------------------------------------------------

admin_dashBoard:
    path:     /velo-admin
    defaults: { _controller: VelovitoBundle:Admin:dashBoard }

admin_api:
    path:     /api/admin/{entity}/{method}
    defaults: {_controller: VelovitoBundle:Admin:api, method: get}


admin_list_products:
    path:     /admin/list-products
    defaults: { _controller: VelovitoBundle:Admin:listProducts }

admin_list_categories:
    path:     /admin/list-categories
    defaults: { _controller: VelovitoBundle:Admin:listCategories }

admin_list_attibutes:
    path:     /admin/list-attributes
    defaults: { _controller: VelovitoBundle:Admin:listAttributes }

admin_edit_attribute:
    path:     /admin/edit-attribute/{id}
    defaults: { _controller: VelovitoBundle:Admin:editAttribute }

admin_list_references:
    path:     /admin/list-references
    defaults: { _controller: VelovitoBundle:Admin:listReferences }

admin_edit_reference:
    path:     /admin/edit-reference/{id}
    defaults: { _controller: VelovitoBundle:Admin:editReference }

admin_toggle_reference_item:
    path:     /admin/toggle-reference-item
    defaults: { _controller: VelovitoBundle:Admin:toggleReferenceItemStatus }

admin_edit_product:
    path:     /admin/edit-product/{id}
    defaults: { _controller: VelovitoBundle:Admin:editProduct }

admin_edit_category:
    path:     /admin/edit-category/{id}
    defaults: { _controller: VelovitoBundle:Admin:editCategory }

#--------------------------------------------------------

ajax_upload_photo:
    path:     /ajax-upload-photo
    defaults: { _controller: VelovitoBundle:Ajax:uploadPhoto }


api_adverts_search:
    path:     /api/search-adverts
    defaults: { _controller: VelovitoBundle:Advert:apiSearchAdvert}

#--------------------------------------------------------

velovito:
    path:     /velovito
    defaults: { _controller: VelovitoBundle:Default:velovito }

homepage:
    path:     /
    defaults: { _controller: VelovitoBundle:Default:index }

catalog:
    path:     /catalog
    defaults: { _controller: VelovitoBundle:Default:index }

settings:
    path:     /settings
    defaults: { _controller: VelovitoBundle:User:settings }

view_user_profile:
    path:     /users/profile/{id}
    defaults: { _controller: VelovitoBundle:User:viewUserProfile }


my_ads:
    path:     /my-adverts
    defaults: { _controller: VelovitoBundle:User:myAds }

favorites:
    path:     /favorite-adverts
    defaults: { _controller: VelovitoBundle:User:favoriteAdverts }

advert_new:
    path:     /new-advert
    defaults: { _controller: VelovitoBundle:Advert:addAdvert }

advert_fill:
    path:     /fill-advert/{id}
    defaults: { _controller: VelovitoBundle:Advert:fillAdvert }

advert_edit_main:
    path:     /edit-advert/{advertId}/main
    defaults: { _controller: VelovitoBundle:Advert:editAdvertMain}

advert_edit_details:
    path:     /edit-advert/{advertId}/details
    defaults: { _controller: VelovitoBundle:Advert:editAdvertDetails}

advert_unpublish:
    path:     /unpublish-advert/{advertId}
    defaults: { _controller: VelovitoBundle:Advert:unpublishAdvert }

advert_delete:
    path:     /unpublish-delete
    defaults: { _controller: VelovitoBundle:Advert:unPublishAdvert }

advert_view:
    path:     /view-advert/{advertId}
    defaults: { _controller: VelovitoBundle:Advert:viewAdvert, advertId: null }

adverts_search:
    path:     /search-adverts
    defaults: { _controller: VelovitoBundle:Advert:searchAdvert, advertId: null }

view_category:
    path:     /view-category
    defaults: { _controller: VelovitoBundle:Advert:viewCategory}
