login_check:
    path: /login-check

logout:
    path: /logout

#routes for real pages
login:
    path: /login
    defaults:
        _controller: VelovitoBundle:Security:login
        title: Вход

registration:
    path: /registration
    defaults:
        _controller: VelovitoBundle:Security:registration
        title: Регистрация

vk_auth:
    path: /vk_auth
    defaults:
        _controller: VelovitoBundle:Security:vkAuth
        title: Регистрация через ВК

#--------------------------------------------------------
ajax_upload_photo:
    path:     /ajax-upload-photo
    defaults: { _controller: VelovitoBundle:Ajax:uploadPhoto }

velovito:
    path:     /velovito
    defaults: { _controller: VelovitoBundle:Default:velovito }

homepage:
    path:     /
    defaults: { _controller: VelovitoBundle:Default:index }

catalog:
    path:     /catalog
    defaults: { _controller: VelovitoBundle:Default:index }


profile:
    path:     /profile
    defaults: { _controller: VelovitoBundle:User:profile }


my_ads:
    path:     /my-adverts
    defaults: { _controller: VelovitoBundle:User:myAds }


favorites:
    path:     /favorite-adverts
    defaults: { _controller: VelovitoBundle:User:favoriteAdverts }

advert_new:
    path:     /new-advert
    defaults: { _controller: VelovitoBundle:Advert:newAdvert }

advert_edit:
    path:     /edit-advert/{advertId}
    defaults: { _controller: VelovitoBundle:Advert:editAdvert}

advert_unpublish:
    path:     /unpublish-advert/{advertId}
    defaults: { _controller: VelovitoBundle:Advert:unpublishAdvert }

advert_delete:
    path:     /unpublish-delete
    defaults: { _controller: VelovitoBundle:Advert:asdAdvert }

advert_view:
    path:     /view-advert/{advertId}
    defaults: { _controller: VelovitoBundle:Advert:viewAdvert, advertId: null }

original_photo:
    path:     /img/originals/{fileName}
    defaults: { _controller: VelovitoBundle:Advert:nullController, fileName: null }

temporary_thumb:
    path:     /img/temporary_thumbs/{fileName}
    defaults: { _controller: VelovitoBundle:Advert:nullController, fileName: null }
