services:
#    VelovitoBundle.example:
#        class: VelovitoBundleBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    model.maintenance:
        class: VelovitoBundle\Model\Maintenance\MaintenanceModel
        arguments: ["@doctrine.orm.entity_manager", "@model.default"]

    model.default:
        class: VelovitoBundle\Model\DefaultModel
        arguments: ["@doctrine.orm.entity_manager", "@kernel", "@session"]

    model.security:
        class: VelovitoBundle\Model\SecurityModel
        arguments: ["@doctrine.orm.entity_manager", "@session", "@security.token_storage", "@model.vk_api", "@model.user"]

    model.admin:
        class: VelovitoBundle\Model\Admin\AdminModel
        arguments: ["@doctrine.orm.entity_manager"]

    model.advertisement:
        class: VelovitoBundle\Model\Advertisement\AdvertisementModel
        arguments: ["@doctrine.orm.entity_manager", "@model.document", "@model.security", "@service.file_worker"]

    model.user:
        class: VelovitoBundle\Model\User\UserModel
        arguments: ["@doctrine.orm.entity_manager", "@session", "@security.token_storage", "@model.vk_api"]

    model.document:
        class: VelovitoBundle\Model\DocumentModel
        arguments: ["@doctrine.orm.entity_manager", "@model.default"]

    model.vk_api:
        class: VelovitoBundle\Model\VkApi\VkApiModel
        arguments: [%vk_api_client_id%, %vk_api_client_secret%, %vk_api_version%, "@router", "@session", "@security.token_storage"]

    service.file_worker:
        class: VelovitoBundle\Service\FileWorker
        arguments: ["@kernel"]

    service.cache:
        class: VelovitoBundle\Service\CacheService
        arguments: ["@doctrine.orm.default_entity_manager"]

    image_service:
        class: VelovitoBundle\Service\GregwarImageService
        arguments: ["@model.default", "@service.file_worker"]

    twig.plural:
        class: VelovitoBundle\Twig\PluralExtension
        tags:
            - { name: twig.extension }

    twig.price:
        class: VelovitoBundle\Twig\PriceExtension
        tags:
            - { name: twig.extension }

    twig.tariff_params:
         class: VelovitoBundle\Twig\TariffParamsExtension
         tags:
             - { name: twig.extension }

    twig.image_service:
         class: VelovitoBundle\Twig\GregwarImageExtension
         arguments: ["@image_service", "@service.file_worker", "@router"]
         tags:
             - { name: twig.extension }

    twig.days_ago:
         class: VelovitoBundle\Twig\DaysAgoExtension
         tags:
             - { name: twig.extension }

    twig.date_format_ru:
         class: VelovitoBundle\Twig\DateFormatRuExtension
         tags:
             - { name: twig.extension }