services:
#    VelovitoBundle.example:
#        class: VelovitoBundleBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    model.maintenance:
        class: VelovitoBundle\Model\Maintenance\MaintenanceModel
        arguments: ["@doctrine.orm.entity_manager"]

    model.default:
        class: VelovitoBundle\Model\DefaultModel
        arguments: ["@doctrine.orm.entity_manager", "@kernel", "@session"]

    model.security:
        class: VelovitoBundle\Model\SecurityModel
        arguments: ["@doctrine.orm.entity_manager", "@kernel"]
