services:
#    VelovitoBundle.example:
#        class: VelovitoBundleBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    model.maintenance:
        class: VelovitoBundle\Model\Maintenance\MaintenanceModel
        arguments: ["@doctrine.orm.entity_manager", "@model.default"]

    model.default:
        class: VelovitoBundle\Model\DefaultModel
        arguments: ["@doctrine.orm.entity_manager", "@kernel", "@session"]

    model.security:
        class: VelovitoBundle\Model\SecurityModel
        arguments: ["@doctrine.orm.entity_manager", "@kernel"]

    model.advertisement:
        class: VelovitoBundle\Model\Advertisement\AdvertisementModel
        arguments: ["@doctrine.orm.entity_manager", "@model.document"]

    model.user:
        class: VelovitoBundle\Model\User\UserModel
        arguments: ["@doctrine.orm.entity_manager", "@kernel"]

    model.document:
        class: VelovitoBundle\Model\DocumentModel
        arguments: ["@doctrine.orm.entity_manager", "@model.default"]

    twig.plural:
        class: VelovitoBundle\Twig\PluralExtension
        tags:
            - { name: twig.extension }

    twig.price:
        class: VelovitoBundle\Twig\PriceExtension
        tags:
            - { name: twig.extension }

    twig.tariff_params:
         class: VelovitoBundle\Twig\TariffParamsExtension
         tags:
             - { name: twig.extension }

    twig.image_service:
         class: VelovitoBundle\Twig\GregwarImageExtension
         tags:
             - { name: twig.extension }

    twig.days_ago:
         class: VelovitoBundle\Twig\DaysAgoExtension
         tags:
             - { name: twig.extension }

    twig.date_format_ru:
         class: VelovitoBundle\Twig\DateFormatRuExtension
         tags:
             - { name: twig.extension }